spring:
  zipkin:
      base-url: http://127.0.0.1:7200
  application:
      name: service-feign
server:
  port: 8083
feign:
  hystrix:
      enabled: true
eureka:
  client:
      serviceUrl:
          defaultZone: http://127.0.0.1:8080/eureka/